# Generated by Django 4.0.6 on 2022-07-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_newdocument_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdocument',
            name='document',
            field=models.FileField(upload_to='img/'),
        ),
    ]
