# Generated by Django 4.0.6 on 2022-07-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comment_owner_pick_updatedraftspot_trade_threadmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='picture',
            field=models.ImageField(blank=True, default='img/default_user.png', upload_to='img/'),
        ),
    ]
