# Generated by Django 4.0.6 on 2022-07-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_owner_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='picture',
            field=models.ImageField(blank=True, default='img/default_user.png', upload_to='img/profile_pics/'),
        ),
    ]
